<?php
header('Cache-Control: no-cache, must-revalidate, max-age=0');
header('Cache-Control: post-check=0, pre-check=0', false);
header('Pragma: no-cache');
header('Expires: 0');
?>

<!DOCTYPE html>
<html lang="fr">
    <HEAD>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="Common/stylecss.css">
        <TITLE>Watteco - Online Codec</TITLE>
        <link rel="shortcut icon" href="Common/cropped-cropped-favicon-300x300-1-32x32.png">

		<script type="text/javascript">
            var activeTabId = "Decoders";
            var toolRoutes = {
                Decoders: { slug: 'decoders', src: 'Decoders/index.php' },
                JSONTohexFrame: { slug: 'json-to-hex', src: 'LoraEncoder/JSONTohexFrame.php' },
                Encoders: { slug: 'encoder-assistant', src: 'LoraEncoder/index.php' },
                EasyCodec: { slug: 'easy-codec', src: 'https://lora.watteco.fr/EasyCodec/tabs/downlink' }
            };

            function TabSelect(id) {
                document.getElementById("Decoders").className="";
                document.getElementById("JSONTohexFrame").className="";
                document.getElementById("Encoders").className="";
                document.getElementById("EasyCodec").className="";
                document.getElementById(id).className="active";
                activeTabId = id;
            }

            function SetIframeSource(src) {
                var iframe = document.querySelector('iframe[name="iframe_a"]');
                var currentIframeUrl = new URL(iframe.src, window.location.href);
                var targetIframeUrl = new URL(src, window.location.href);

                if (currentIframeUrl.href !== targetIframeUrl.href) {
                    iframe.src = src;
                }
            }

            function GetAddressParams() {
                var params = new URLSearchParams(window.location.search);
                if (!params.has('tool') && !params.has('trame') && !params.has('trameBatch')) {
                    // Compatibility with links generated by the first sharing implementation.
                    var legacyParams = new URLSearchParams(window.location.hash.replace(/^#/, ''));
                    if (legacyParams.has('tool')) params = legacyParams;
                }
                return params;
            }

            function GetDecoderIframeUrl(params) {
                var decoderParams = new URLSearchParams();
                var mode = params.has('trameBatch') || params.get('mode') === 'batch' ? 'batch' : 'standard';
                var frame = params.get(mode === 'batch' ? 'trameBatch' : 'trame');
                if (frame === null) frame = params.get('frame');

                if (params.has('mode')) decoderParams.set('mode', mode);

                if (mode === 'batch') {
                    if (frame) {
                        decoderParams.set('trameBatch', frame);
                        decoderParams.set(' submit', 'Submit2');
                    }
                    decoderParams.set('timestamp', params.get('timestamp') || '');
                    decoderParams.set('BatchAttributes', params.get('BatchAttributes') || params.get('attributes') || '');
                    if (params.has('checkbasebatch') || params.get('base64') === '1') {
                        decoderParams.set('checkbasebatch', 'checkox_value');
                    }
                } else {
                    if (frame) {
                        decoderParams.set('trame', frame);
                        decoderParams.set(' submit', 'Submit');
                    }
                    if (frame || params.has('MySelectMenu') || params.has('format')) {
                        decoderParams.set('MySelectMenu', params.get('MySelectMenu') || params.get('format') || '0');
                    }
                    if (params.has('checkbase') || params.get('base64') === '1') {
                        decoderParams.set('checkbase', 'checkox_value');
                    }
                }

                var query = decoderParams.toString();
                return toolRoutes.Decoders.src + (query ? '?' + query : '');
            }

            function GetJsonToHexIframeUrl(params) {
                var encoderParams = new URLSearchParams();

                if (params.has('trame')) {
                    encoderParams.set('trame', params.get('trame'));
                    encoderParams.set(' submit', 'Submit');
                }

                var query = encoderParams.toString();
                return toolRoutes.JSONTohexFrame.src + (query ? '?' + query : '');
            }

            function GetToolId(params) {
                var requestedSlug = params.get('tool');
                var requestedTool = Object.keys(toolRoutes).find(function(id) {
                    return toolRoutes[id].slug === requestedSlug;
                });

                if (requestedTool) return requestedTool;
                if (params.has('trame') || params.has('trameBatch')) return 'Decoders';
                return 'Decoders';
            }

            function RestoreToolFromAddress() {
                var params = GetAddressParams();
                var toolId = GetToolId(params);
                var iframeUrl = toolRoutes[toolId].src;
                if (toolId === 'Decoders') iframeUrl = GetDecoderIframeUrl(params);
                if (toolId === 'JSONTohexFrame') iframeUrl = GetJsonToHexIframeUrl(params);

                SetIframeSource(iframeUrl);
                TabSelect(toolId);
            }

            function OpenTool(event, id) {
                if ((event.button !== undefined && event.button !== 0) || event.ctrlKey || event.metaKey || event.shiftKey || event.altKey) {
                    return true;
                }

                event.preventDefault();
                var targetUrl = new URL('/Lora/', window.location.origin);
                targetUrl.searchParams.set('tool', toolRoutes[id].slug);
                window.history.pushState(null, '', targetUrl.href);
                RestoreToolFromAddress();
                return false;
            }

            function UpdateDecoderMode(mode) {
                var targetUrl = new URL('/Lora/', window.location.origin);
                targetUrl.searchParams.set('tool', 'decoders');
                targetUrl.searchParams.set('mode', mode === 'batch' ? 'batch' : 'standard');
                window.history.pushState(null, '', targetUrl.href);
                TabSelect('Decoders');
            }

            window.addEventListener('DOMContentLoaded', RestoreToolFromAddress);
            window.addEventListener('hashchange', RestoreToolFromAddress);
            window.addEventListener('popstate', RestoreToolFromAddress);
        </script>
    </HEAD>
    <BODY class="app-shell">
        <header id="header">
            <a href="https://support.watteco.com/"  target="_blank">
                <img class="header-logo" src="Common/Logo-Watteco-rdm.png" style="float: left" width="100" height="auto" alt="">
            </a>   
            <h2 id="mainMainTitle" style="text-align: center;">
                <span style="text-decoration: underline;">ONLINE SENSORS CODECS</span>
            </h2>
        </header>
		<div id="menu">
			<ul id="onglets">
				<li id="Decoders" class="active"><a href="/Lora/?tool=decoders" onClick="return OpenTool(event, 'Decoders');">  Decoders  </a></li>
				<li id="JSONTohexFrame"><a href="/Lora/?tool=json-to-hex" onClick="return OpenTool(event, 'JSONTohexFrame');">  JSON to Hex encoder</a></li>
                <li id="Encoders"><a href="/Lora/?tool=encoder-assistant" onClick="return OpenTool(event, 'Encoders');">  Encoder assistant  </a></li>
				<li id="EasyCodec"><a href="/Lora/?tool=easy-codec" onClick="return OpenTool(event, 'EasyCodec');">  Easy Codec  </a></li>
			</ul>
		</div>
		<div id="wrapper">
            <iframe name="iframe_a" title="Iframe container" src="Decoders/index.php"></iframe>
        </div>
    </BODY>
</HTML>
